/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // Code coverage
    id("jacoco")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // JUnit Jupiter (JUnit 5) for testing
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    
    // Mockito for mocking
    testImplementation("org.mockito:mockito-core:5.8.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.8.0")
    
    // Gson for JSON serialization
    implementation("com.google.code.gson:gson:2.10.1")
    
    // Apache Commons Math for optimization algorithms
    implementation("org.apache.commons:commons-math3:3.6.1")
    
    // Google OR-Tools for constraint programming and optimization
    implementation("com.google.ortools:ortools-java:9.8.3296")
    
    // This dependency is used by the application.
    implementation(libs.guava)

    // Note: No JavaFX plugin/dependencies here. The project includes a lightweight
    // Swing-based GUI so no external GUI plugin is required for compilation.
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "archdesign.Main"
}

// Add a convenience task to run the GUI application from Gradle
tasks.register<JavaExec>("runGui") {
    group = "application"
    description = "Run the GUI application (Swing)"
    classpath = sourceSets.main.get().runtimeClasspath
    // Use the Kotlin DSL property for main class
    this.mainClass.set("archdesign.gui.GuiApp")
}

// Produce a "fat" (uber) JAR that bundles runtime dependencies. This is
// intentionally simple and works cross-platform for manual jpackage usage
// or for users who just want a single JAR to double-click with a matching
// JRE. The produced archive will be available as
// app/build/libs/<project>-<version>-all.jar
tasks.register<Jar>("fatJar") {
    archiveClassifier.set("all")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().output)
    // Unpack runtime classpath jars into the fat jar
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith(".jar") }.map { zipTree(it) }
    })
    manifest {
        attributes["Main-Class"] = "archdesign.Main"
    }
}

// Produce a fat JAR specifically for launching the GUI (Swing) so double-click
// will open the GUI instead of running the CLI. This produces a separate
// artifact with a different classifier so both CLI and GUI jars can coexist.
tasks.register<Jar>("fatJarGui") {
    archiveClassifier.set("gui-all")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().output)
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith(".jar") }.map { zipTree(it) }
    })
    manifest {
        attributes["Main-Class"] = "archdesign.gui.GuiApp"
    }
}

// Note: Packaging into native installers (MSI/EXE/DMG/PKG) can be done
// with `jpackage` or via Gradle plugins (org.beryx.runtime) but that plugin
// is intentionally not applied here to avoid repository-specific plugin
// resolution issues. See README for manual jpackage guidance.

// No JavaFX configuration; the GUI provided is Swing-based and requires only
// standard Java SE APIs so it compiles with the existing toolchain.

// Note: runtime (jpackage) support can be added by enabling the org.beryx.runtime
// Gradle plugin and configuring the `runtime` block. The plugin was intentionally
// removed here to avoid plugin resolution issues in environments where the plugin
// cannot be resolved. See README for guidance on packaging with jpackage.

tasks.named<Test>("test") {
    useJUnitPlatform()
    
    testLogging {
        events("passed", "skipped", "failed", "standardOut", "standardError")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
        showStandardStreams = true
    }
}

jacoco {
    toolVersion = "0.8.10"
}

tasks.named<JacocoReport>("jacocoTestReport") {
    dependsOn(tasks.named("test"))
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    classDirectories.setFrom(files(listOf(fileTree("${project.buildDir}/classes/java/main"))))
    sourceDirectories.setFrom(files(listOf(file("src/main/java"))))
    executionData.setFrom(files("${project.buildDir}/jacoco/test.exec"))
}
