/*
 * This source file was generated by the Gradle 'init' task
 */
package archdesign;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    // Example JUnit 5 test (kept commented until App exists)
    // @Test
    // public void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
